### ISSUE TITLE
[1pt] Setup Kanban board

### ISSUE THREAD

**Issue by iamchristianani** [Kashif-Saleem-Ghuman/catalog#23]
In this Pull Request, we completed the following:

- Create a project Kanban board.
- Divided tasks equally.
- Each task is a separate card.
- Team members:
   - Team member 1: @Kashif-Saleem-Ghuman 
   - Team member 2: @iamchristianani 
   - Team member 3: @Ellon-M 
- Link to Kanban: [Kanban Board](https://github.com/Kashif-Saleem-Ghuman/catalog/projects/1)

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @Ellon-M @Kashif-Saleem-Ghuman @iamchristianani 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
